-- Combined migrations 0001-0011, generated by scripts/combine-migrations.mjs.
-- Each source file is idempotent, so this whole script is safe to re-run.
-- Source of truth is the individual files in supabase/migrations/ — regenerate
-- this if you add a new one, don't hand-edit it.

-- ============================================================
-- 0001_profiles.sql
-- ============================================================
-- Profiles: one row per authenticated user, keyed to auth.users.
-- Created automatically on signup via a trigger (see below) so the app
-- never has to handle a "missing profile" race after signup.

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,

  display_name text,
  username text unique,
  espn_team_id integer,
  avatar_url text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint profiles_username_format check (
    username is null or username ~ '^[a-z0-9_]{3,24}$'
  )
);

create index if not exists profiles_espn_team_id_idx on public.profiles (espn_team_id);

alter table public.profiles enable row level security;

-- League members can read each other's profiles (display name, avatar, team)
-- but only the owning user can modify their own row.
drop policy if exists "Profiles are readable by authenticated users" on public.profiles;
create policy "Profiles are readable by authenticated users"
on public.profiles
for select
to authenticated
using (true);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

create or replace function public.touch_profiles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.touch_profiles_updated_at();

-- Auto-create a profile row whenever a new auth user is created, seeding
-- display_name from the email so the UI never shows a blank name.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, split_part(new.email, '@', 1))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists trg_handle_new_user on auth.users;
create trigger trg_handle_new_user
after insert on auth.users
for each row execute function public.handle_new_user();

-- ============================================================
-- 0002_player_identity_cache.sql
-- ============================================================
-- Player identity cache for an ESPN + Sleeper fantasy app.
-- Run this in Supabase SQL Editor or via Supabase migrations.

create table if not exists public.player_identity_cache (
  id bigint generated by default as identity primary key,

  sleeper_id text unique,
  espn_id bigint unique,

  full_name text,
  first_name text,
  last_name text,
  position text,
  nfl_team text,
  status text,

  headshot_url text,

  -- Platform ranking/coverage metadata.
  sleeper_rank integer,
  espn_rank integer,
  in_sleeper_top_1000 boolean not null default false,
  in_espn_top_1000 boolean not null default false,

  -- Useful for debugging mappings and refreshing stale records.
  mapping_source text,
  sleeper_updated_at timestamptz,
  espn_updated_at timestamptz,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),

  constraint player_identity_cache_has_identity
    check (sleeper_id is not null or espn_id is not null)
);

create index if not exists player_identity_cache_sleeper_id_idx
  on public.player_identity_cache (sleeper_id);

create index if not exists player_identity_cache_espn_id_idx
  on public.player_identity_cache (espn_id);

create index if not exists player_identity_cache_sleeper_rank_idx
  on public.player_identity_cache (sleeper_rank)
  where in_sleeper_top_1000 = true;

create index if not exists player_identity_cache_espn_rank_idx
  on public.player_identity_cache (espn_rank)
  where in_espn_top_1000 = true;

create index if not exists player_identity_cache_name_idx
  on public.player_identity_cache (full_name);

-- Public read is safe because this table contains only public player metadata.
alter table public.player_identity_cache enable row level security;

drop policy if exists "Public can read player cache" on public.player_identity_cache;
create policy "Public can read player cache"
on public.player_identity_cache
for select
to anon, authenticated
using (true);

-- Do not create public insert/update/delete policies.
-- Sync writes should use the Supabase service-role key server-side only.

create or replace function public.touch_player_identity_cache_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_player_identity_cache_updated_at
  on public.player_identity_cache;
create trigger trg_player_identity_cache_updated_at
before update on public.player_identity_cache
for each row execute function public.touch_player_identity_cache_updated_at();

-- ============================================================
-- 0003_league_data.sql
-- ============================================================
-- Normalized ESPN league data. Written exclusively by the server-side sync
-- job (src/lib/sync/league.ts, via the service-role client) — every table
-- here is read-only to regular authenticated users via RLS.

create table if not exists public.leagues (
  id bigint generated by default as identity primary key,
  espn_league_id bigint not null unique,
  name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  league_id bigint not null references public.leagues (id) on delete cascade,
  season_year integer not null,
  current_week integer,
  is_current boolean not null default false,
  regular_season_matchup_count integer,
  playoff_team_count integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (league_id, season_year)
);

create index if not exists seasons_league_id_idx on public.seasons (league_id);

create table if not exists public.fantasy_teams (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons (id) on delete cascade,
  espn_team_id integer not null,
  name text not null,
  abbrev text,
  logo_url text,
  division_id integer,
  primary_owner_espn_member_id text,
  owner_espn_member_ids text[] not null default '{}',
  wins integer not null default 0,
  losses integer not null default 0,
  ties integer not null default 0,
  points_for numeric not null default 0,
  points_against numeric not null default 0,
  streak_type text,
  streak_length integer,
  playoff_seed integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (season_id, espn_team_id)
);

create index if not exists fantasy_teams_season_id_idx on public.fantasy_teams (season_id);

create table if not exists public.team_rosters (
  id bigint generated by default as identity primary key,
  fantasy_team_id bigint not null references public.fantasy_teams (id) on delete cascade,
  week integer not null,
  espn_player_id bigint not null,
  -- Best-effort resolution against player_identity_cache at sync time.
  -- Nullable because a roster can include deep-bench/IDP players outside
  -- the cache's top-1000 union — full_name below is the fallback display.
  player_identity_cache_id bigint references public.player_identity_cache (id) on delete set null,
  full_name text not null,
  position text,
  nfl_team text,
  lineup_slot text not null,
  is_starter boolean not null default false,
  injury_status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (fantasy_team_id, week, espn_player_id)
);

create index if not exists team_rosters_fantasy_team_id_idx on public.team_rosters (fantasy_team_id);
create index if not exists team_rosters_player_identity_cache_id_idx on public.team_rosters (player_identity_cache_id);

create table if not exists public.matchups (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons (id) on delete cascade,
  espn_matchup_id integer not null,
  week integer not null,
  is_playoff boolean not null default false,
  home_team_id bigint not null references public.fantasy_teams (id) on delete cascade,
  away_team_id bigint references public.fantasy_teams (id) on delete cascade,
  home_score numeric not null default 0,
  away_score numeric,
  result text not null default 'UNDECIDED',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (season_id, espn_matchup_id),
  constraint matchups_result_check check (result in ('HOME', 'AWAY', 'TIE', 'UNDECIDED'))
);

create index if not exists matchups_season_id_week_idx on public.matchups (season_id, week);

create table if not exists public.weekly_team_scores (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons (id) on delete cascade,
  week integer not null,
  fantasy_team_id bigint not null references public.fantasy_teams (id) on delete cascade,
  points numeric not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (season_id, week, fantasy_team_id)
);

create index if not exists weekly_team_scores_season_week_idx on public.weekly_team_scores (season_id, week);

-- Historical, week-by-week standings — populated on every sync so Phase 5
-- (power rankings/luck) and Phase 7 (recaps) have real trend data to read
-- instead of needing to backfill it later.
create table if not exists public.standings_snapshots (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons (id) on delete cascade,
  week integer not null,
  fantasy_team_id bigint not null references public.fantasy_teams (id) on delete cascade,
  rank integer not null,
  wins integer not null,
  losses integer not null,
  ties integer not null,
  points_for numeric not null,
  points_against numeric not null,
  created_at timestamptz not null default now(),
  unique (season_id, week, fantasy_team_id)
);

create index if not exists standings_snapshots_season_week_idx on public.standings_snapshots (season_id, week);

create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  sync_type text not null,
  status text not null default 'running',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  error text,
  meta jsonb,
  created_at timestamptz not null default now(),
  constraint sync_runs_status_check check (status in ('running', 'success', 'error'))
);

create index if not exists sync_runs_sync_type_started_at_idx on public.sync_runs (sync_type, started_at desc);

-- RLS: every table here is league data, safe for any authenticated league
-- member to read. Nothing is publicly writable — only the service-role
-- sync job writes, which bypasses RLS entirely.
do $$
declare
  t text;
begin
  for t in select unnest(array[
    'leagues', 'seasons', 'fantasy_teams', 'team_rosters',
    'matchups', 'weekly_team_scores', 'standings_snapshots', 'sync_runs'
  ])
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "Authenticated users can read %I" on public.%I', t, t);
    execute format(
      'create policy "Authenticated users can read %I" on public.%I for select to authenticated using (true)',
      t, t
    );
  end loop;
end $$;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  t text;
begin
  for t in select unnest(array[
    'leagues', 'seasons', 'fantasy_teams', 'team_rosters', 'matchups', 'weekly_team_scores'
  ])
  loop
    execute format('drop trigger if exists trg_%I_updated_at on public.%I', t, t);
    execute format(
      'create trigger trg_%I_updated_at before update on public.%I for each row execute function public.touch_updated_at()',
      t, t
    );
  end loop;
end $$;

-- ============================================================
-- 0004_watchlist.sql
-- ============================================================
-- User-specific player watchlist. Every authenticated user manages only
-- their own rows — enforced by RLS, not just the UI.

create table if not exists public.watchlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  player_id bigint not null references public.player_identity_cache (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, player_id)
);

create index if not exists watchlist_user_id_idx on public.watchlist (user_id);
create index if not exists watchlist_player_id_idx on public.watchlist (player_id);

alter table public.watchlist enable row level security;

drop policy if exists "Users can read their own watchlist" on public.watchlist;
create policy "Users can read their own watchlist"
on public.watchlist
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert into their own watchlist" on public.watchlist;
create policy "Users can insert into their own watchlist"
on public.watchlist
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can delete from their own watchlist" on public.watchlist;
create policy "Users can delete from their own watchlist"
on public.watchlist
for delete
to authenticated
using (auth.uid() = user_id);

-- ============================================================
-- 0005_trade_block.sql
-- ============================================================
-- League trade block. Everyone in the league can read every entry; only
-- the fantasy team's associated owner (derived from profiles.espn_team_id,
-- never a client-supplied team id) can add/remove their own team's
-- entries.

create table if not exists public.trade_block (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.fantasy_teams (id) on delete cascade,
  player_id bigint not null references public.player_identity_cache (id) on delete cascade,
  added_by uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (team_id, player_id)
);

create index if not exists trade_block_team_id_idx on public.trade_block (team_id);

alter table public.trade_block enable row level security;

drop policy if exists "Authenticated users can read the trade block" on public.trade_block;
create policy "Authenticated users can read the trade block"
on public.trade_block
for select
to authenticated
using (true);

-- A user may modify a trade_block row only if their profile's
-- espn_team_id matches the ESPN team id behind team_id, for that team's
-- (current) season. This is enforced here, not just in application code,
-- so a bug in the Server Action can't grant cross-team write access.
drop policy if exists "Team owners can add to their own trade block" on public.trade_block;
create policy "Team owners can add to their own trade block"
on public.trade_block
for insert
to authenticated
with check (
  added_by = auth.uid()
  and exists (
    select 1
    from public.fantasy_teams ft
    join public.profiles p on p.espn_team_id = ft.espn_team_id
    where ft.id = trade_block.team_id
      and p.id = auth.uid()
  )
);

drop policy if exists "Team owners can remove from their own trade block" on public.trade_block;
create policy "Team owners can remove from their own trade block"
on public.trade_block
for delete
to authenticated
using (
  exists (
    select 1
    from public.fantasy_teams ft
    join public.profiles p on p.espn_team_id = ft.espn_team_id
    where ft.id = trade_block.team_id
      and p.id = auth.uid()
  )
);

-- Realtime: trade_block changes need to reach other logged-in browsers
-- live (src/components/trades/realtime-refresh.tsx subscribes to this).
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'trade_block'
  ) then
    alter publication supabase_realtime add table public.trade_block;
  end if;
end $$;

-- Future trade interest ("I'm Interested" on a trade-block entry). Schema
-- only for now — not exposed in the UI yet.
create table if not exists public.trade_interest (
  id bigint generated by default as identity primary key,
  trade_block_id bigint not null references public.trade_block (id) on delete cascade,
  interested_user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (trade_block_id, interested_user_id)
);

alter table public.trade_interest enable row level security;

drop policy if exists "Authenticated users can read trade interest" on public.trade_interest;
create policy "Authenticated users can read trade interest"
on public.trade_interest
for select
to authenticated
using (true);

drop policy if exists "Users can express their own interest" on public.trade_interest;
create policy "Users can express their own interest"
on public.trade_interest
for insert
to authenticated
with check (interested_user_id = auth.uid());

drop policy if exists "Users can withdraw their own interest" on public.trade_interest;
create policy "Users can withdraw their own interest"
on public.trade_interest
for delete
to authenticated
using (interested_user_id = auth.uid());

-- ============================================================
-- 0006_power_rankings.sql
-- ============================================================
-- Weekly power rankings, stored historically so movement (rank vs
-- previous_rank) doesn't need to be recomputed from scratch every time.
-- Written by src/lib/sync/power-rankings.ts. See docs/analytics.md for the
-- formula and weight config.

create table if not exists public.power_rankings (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons (id) on delete cascade,
  week integer not null,
  team_id bigint not null references public.fantasy_teams (id) on delete cascade,
  rank integer not null,
  previous_rank integer,
  power_score numeric not null,
  all_play_score numeric not null,
  points_score numeric not null,
  recent_score numeric not null,
  record_score numeric not null,
  roster_score numeric not null,
  created_at timestamptz not null default now(),
  unique (season_id, week, team_id)
);

create index if not exists power_rankings_season_week_idx on public.power_rankings (season_id, week);

alter table public.power_rankings enable row level security;

drop policy if exists "Authenticated users can read power rankings" on public.power_rankings;
create policy "Authenticated users can read power rankings"
on public.power_rankings
for select
to authenticated
using (true);

-- ============================================================
-- 0007_fantasy_teams_final_rank.sql
-- ============================================================
-- ESPN's final standing for a completed season (team.rankCalculatedFinal /
-- team.rankFinal in the raw response) — the authoritative source for who
-- won the league, used by the Champions page. 0/absent for an in-progress
-- season.
alter table public.fantasy_teams add column if not exists final_rank integer;

-- ============================================================
-- 0008_chat.sql
-- ============================================================
-- Simple league-wide chat. Every authenticated league member can read and
-- post; a message's author is always the authenticated session's user_id
-- (never client-supplied) — the UI resolves the display name via profiles
-- at read time, never by trusting a client-sent name.

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_created_at_idx on public.chat_messages (created_at desc);

alter table public.chat_messages enable row level security;

drop policy if exists "Authenticated users can read chat" on public.chat_messages;
create policy "Authenticated users can read chat"
on public.chat_messages
for select
to authenticated
using (true);

drop policy if exists "Users can post chat as themselves" on public.chat_messages;
create policy "Users can post chat as themselves"
on public.chat_messages
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can delete their own messages" on public.chat_messages;
create policy "Users can delete their own messages"
on public.chat_messages
for delete
to authenticated
using (user_id = auth.uid());

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'chat_messages'
  ) then
    alter publication supabase_realtime add table public.chat_messages;
  end if;
end $$;

-- ============================================================
-- 0009_weekly_recaps.sql
-- ============================================================
-- Completed weekly recaps. Stored as a JSON payload (see
-- src/lib/analytics/recap.ts for the shape) rather than a column per
-- field — the recap's content is naturally a small nested document, and
-- keeping it flexible here means a later LLM-generated narrative field can
-- be added without a migration. season/week/created_at stay as real
-- columns since those are what queries filter and sort on.

create table if not exists public.weekly_recaps (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons (id) on delete cascade,
  week integer not null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  unique (season_id, week)
);

create index if not exists weekly_recaps_season_week_idx on public.weekly_recaps (season_id, week);

alter table public.weekly_recaps enable row level security;

drop policy if exists "Authenticated users can read weekly recaps" on public.weekly_recaps;
create policy "Authenticated users can read weekly recaps"
on public.weekly_recaps
for select
to authenticated
using (true);

-- ============================================================
-- 0010_youtube.sql
-- ============================================================
-- Configured YouTube channels + a cache of their latest videos, so the
-- Media page never calls YouTube at request time (see
-- src/lib/youtube/service.ts and src/lib/sync/youtube.ts).

create table if not exists public.youtube_channels (
  id bigint generated by default as identity primary key,
  name text not null,
  channel_id text not null unique,
  handle text,
  enabled boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.youtube_videos_cache (
  id bigint generated by default as identity primary key,
  channel_id text not null references public.youtube_channels (channel_id) on delete cascade,
  video_id text not null,
  title text not null,
  thumbnail_url text,
  published_at timestamptz,
  fetched_at timestamptz not null default now(),
  unique (channel_id, video_id)
);

create index if not exists youtube_videos_cache_channel_id_idx on public.youtube_videos_cache (channel_id, published_at desc);

alter table public.youtube_channels enable row level security;
alter table public.youtube_videos_cache enable row level security;

drop policy if exists "Authenticated users can read youtube channels" on public.youtube_channels;
create policy "Authenticated users can read youtube channels"
on public.youtube_channels
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read cached videos" on public.youtube_videos_cache;
create policy "Authenticated users can read cached videos"
on public.youtube_videos_cache
for select
to authenticated
using (true);

-- Seed the channel provided when this app was set up. Safe to re-run.
insert into public.youtube_channels (name, channel_id, enabled, display_order)
values ('League Channel', 'UCwVcTSzyshT2gMZZFhkiA-Q', true, 0)
on conflict (channel_id) do nothing;

-- ============================================================
-- 0011_profiles_unique_team.sql
-- ============================================================
-- Each ESPN fantasy team should be claimed by at most one profile.
-- Postgres unique constraints treat NULLs as distinct from each other, so
-- any number of profiles can still have espn_team_id = null (unclaimed).
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'profiles_espn_team_id_unique'
  ) then
    alter table public.profiles
      add constraint profiles_espn_team_id_unique unique (espn_team_id);
  end if;
end $$;
