-- Player identity cache for an ESPN + Sleeper fantasy app.
-- Run this in Supabase SQL Editor or via Supabase migrations.

create table if not exists public.player_identity_cache (
  id bigint generated by default as identity primary key,

  sleeper_id text unique,
  espn_id bigint unique,

  full_name text,
  first_name text,
  last_name text,
  position text,
  nfl_team text,
  status text,

  headshot_url text,

  -- Platform ranking/coverage metadata.
  sleeper_rank integer,
  espn_rank integer,
  in_sleeper_top_1000 boolean not null default false,
  in_espn_top_1000 boolean not null default false,

  -- Useful for debugging mappings and refreshing stale records.
  mapping_source text,
  sleeper_updated_at timestamptz,
  espn_updated_at timestamptz,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),

  constraint player_identity_cache_has_identity
    check (sleeper_id is not null or espn_id is not null)
);

create index if not exists player_identity_cache_sleeper_id_idx
  on public.player_identity_cache (sleeper_id);

create index if not exists player_identity_cache_espn_id_idx
  on public.player_identity_cache (espn_id);

create index if not exists player_identity_cache_sleeper_rank_idx
  on public.player_identity_cache (sleeper_rank)
  where in_sleeper_top_1000 = true;

create index if not exists player_identity_cache_espn_rank_idx
  on public.player_identity_cache (espn_rank)
  where in_espn_top_1000 = true;

create index if not exists player_identity_cache_name_idx
  on public.player_identity_cache (full_name);

-- Public read is safe because this table contains only public player metadata.
alter table public.player_identity_cache enable row level security;

drop policy if exists "Public can read player cache" on public.player_identity_cache;
create policy "Public can read player cache"
on public.player_identity_cache
for select
to anon, authenticated
using (true);

-- Do not create public insert/update/delete policies.
-- Sync writes should use the Supabase service-role key server-side only.

create or replace function public.touch_player_identity_cache_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_player_identity_cache_updated_at
  on public.player_identity_cache;
create trigger trg_player_identity_cache_updated_at
before update on public.player_identity_cache
for each row execute function public.touch_player_identity_cache_updated_at();
