-- Normalized ESPN league data. Written exclusively by the server-side sync
-- job (src/lib/sync/league.ts, via the service-role client) — every table
-- here is read-only to regular authenticated users via RLS.

create table if not exists public.leagues (
  id bigint generated by default as identity primary key,
  espn_league_id bigint not null unique,
  name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  league_id bigint not null references public.leagues (id) on delete cascade,
  season_year integer not null,
  current_week integer,
  is_current boolean not null default false,
  regular_season_matchup_count integer,
  playoff_team_count integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (league_id, season_year)
);

create index if not exists seasons_league_id_idx on public.seasons (league_id);

create table if not exists public.fantasy_teams (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons (id) on delete cascade,
  espn_team_id integer not null,
  name text not null,
  abbrev text,
  logo_url text,
  division_id integer,
  primary_owner_espn_member_id text,
  owner_espn_member_ids text[] not null default '{}',
  wins integer not null default 0,
  losses integer not null default 0,
  ties integer not null default 0,
  points_for numeric not null default 0,
  points_against numeric not null default 0,
  streak_type text,
  streak_length integer,
  playoff_seed integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (season_id, espn_team_id)
);

create index if not exists fantasy_teams_season_id_idx on public.fantasy_teams (season_id);

create table if not exists public.team_rosters (
  id bigint generated by default as identity primary key,
  fantasy_team_id bigint not null references public.fantasy_teams (id) on delete cascade,
  week integer not null,
  espn_player_id bigint not null,
  -- Best-effort resolution against player_identity_cache at sync time.
  -- Nullable because a roster can include deep-bench/IDP players outside
  -- the cache's top-1000 union — full_name below is the fallback display.
  player_identity_cache_id bigint references public.player_identity_cache (id) on delete set null,
  full_name text not null,
  position text,
  nfl_team text,
  lineup_slot text not null,
  is_starter boolean not null default false,
  injury_status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (fantasy_team_id, week, espn_player_id)
);

create index if not exists team_rosters_fantasy_team_id_idx on public.team_rosters (fantasy_team_id);
create index if not exists team_rosters_player_identity_cache_id_idx on public.team_rosters (player_identity_cache_id);

create table if not exists public.matchups (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons (id) on delete cascade,
  espn_matchup_id integer not null,
  week integer not null,
  is_playoff boolean not null default false,
  home_team_id bigint not null references public.fantasy_teams (id) on delete cascade,
  away_team_id bigint references public.fantasy_teams (id) on delete cascade,
  home_score numeric not null default 0,
  away_score numeric,
  result text not null default 'UNDECIDED',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (season_id, espn_matchup_id),
  constraint matchups_result_check check (result in ('HOME', 'AWAY', 'TIE', 'UNDECIDED'))
);

create index if not exists matchups_season_id_week_idx on public.matchups (season_id, week);

create table if not exists public.weekly_team_scores (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons (id) on delete cascade,
  week integer not null,
  fantasy_team_id bigint not null references public.fantasy_teams (id) on delete cascade,
  points numeric not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (season_id, week, fantasy_team_id)
);

create index if not exists weekly_team_scores_season_week_idx on public.weekly_team_scores (season_id, week);

-- Historical, week-by-week standings — populated on every sync so Phase 5
-- (power rankings/luck) and Phase 7 (recaps) have real trend data to read
-- instead of needing to backfill it later.
create table if not exists public.standings_snapshots (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons (id) on delete cascade,
  week integer not null,
  fantasy_team_id bigint not null references public.fantasy_teams (id) on delete cascade,
  rank integer not null,
  wins integer not null,
  losses integer not null,
  ties integer not null,
  points_for numeric not null,
  points_against numeric not null,
  created_at timestamptz not null default now(),
  unique (season_id, week, fantasy_team_id)
);

create index if not exists standings_snapshots_season_week_idx on public.standings_snapshots (season_id, week);

create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  sync_type text not null,
  status text not null default 'running',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  error text,
  meta jsonb,
  created_at timestamptz not null default now(),
  constraint sync_runs_status_check check (status in ('running', 'success', 'error'))
);

create index if not exists sync_runs_sync_type_started_at_idx on public.sync_runs (sync_type, started_at desc);

-- RLS: every table here is league data, safe for any authenticated league
-- member to read. Nothing is publicly writable — only the service-role
-- sync job writes, which bypasses RLS entirely.
do $$
declare
  t text;
begin
  for t in select unnest(array[
    'leagues', 'seasons', 'fantasy_teams', 'team_rosters',
    'matchups', 'weekly_team_scores', 'standings_snapshots', 'sync_runs'
  ])
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "Authenticated users can read %I" on public.%I', t, t);
    execute format(
      'create policy "Authenticated users can read %I" on public.%I for select to authenticated using (true)',
      t, t
    );
  end loop;
end $$;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  t text;
begin
  for t in select unnest(array[
    'leagues', 'seasons', 'fantasy_teams', 'team_rosters', 'matchups', 'weekly_team_scores'
  ])
  loop
    execute format('drop trigger if exists trg_%I_updated_at on public.%I', t, t);
    execute format(
      'create trigger trg_%I_updated_at before update on public.%I for each row execute function public.touch_updated_at()',
      t, t
    );
  end loop;
end $$;
