-- User-specific player watchlist. Every authenticated user manages only
-- their own rows — enforced by RLS, not just the UI.

create table if not exists public.watchlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  player_id bigint not null references public.player_identity_cache (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, player_id)
);

create index if not exists watchlist_user_id_idx on public.watchlist (user_id);
create index if not exists watchlist_player_id_idx on public.watchlist (player_id);

alter table public.watchlist enable row level security;

drop policy if exists "Users can read their own watchlist" on public.watchlist;
create policy "Users can read their own watchlist"
on public.watchlist
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert into their own watchlist" on public.watchlist;
create policy "Users can insert into their own watchlist"
on public.watchlist
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can delete from their own watchlist" on public.watchlist;
create policy "Users can delete from their own watchlist"
on public.watchlist
for delete
to authenticated
using (auth.uid() = user_id);
