-- League trade block. Everyone in the league can read every entry; only
-- the fantasy team's associated owner (derived from profiles.espn_team_id,
-- never a client-supplied team id) can add/remove their own team's
-- entries.

create table if not exists public.trade_block (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.fantasy_teams (id) on delete cascade,
  player_id bigint not null references public.player_identity_cache (id) on delete cascade,
  added_by uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (team_id, player_id)
);

create index if not exists trade_block_team_id_idx on public.trade_block (team_id);

alter table public.trade_block enable row level security;

drop policy if exists "Authenticated users can read the trade block" on public.trade_block;
create policy "Authenticated users can read the trade block"
on public.trade_block
for select
to authenticated
using (true);

-- A user may modify a trade_block row only if their profile's
-- espn_team_id matches the ESPN team id behind team_id, for that team's
-- (current) season. This is enforced here, not just in application code,
-- so a bug in the Server Action can't grant cross-team write access.
drop policy if exists "Team owners can add to their own trade block" on public.trade_block;
create policy "Team owners can add to their own trade block"
on public.trade_block
for insert
to authenticated
with check (
  added_by = auth.uid()
  and exists (
    select 1
    from public.fantasy_teams ft
    join public.profiles p on p.espn_team_id = ft.espn_team_id
    where ft.id = trade_block.team_id
      and p.id = auth.uid()
  )
);

drop policy if exists "Team owners can remove from their own trade block" on public.trade_block;
create policy "Team owners can remove from their own trade block"
on public.trade_block
for delete
to authenticated
using (
  exists (
    select 1
    from public.fantasy_teams ft
    join public.profiles p on p.espn_team_id = ft.espn_team_id
    where ft.id = trade_block.team_id
      and p.id = auth.uid()
  )
);

-- Realtime: trade_block changes need to reach other logged-in browsers
-- live (src/components/trades/realtime-refresh.tsx subscribes to this).
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'trade_block'
  ) then
    alter publication supabase_realtime add table public.trade_block;
  end if;
end $$;

-- Future trade interest ("I'm Interested" on a trade-block entry). Schema
-- only for now — not exposed in the UI yet.
create table if not exists public.trade_interest (
  id bigint generated by default as identity primary key,
  trade_block_id bigint not null references public.trade_block (id) on delete cascade,
  interested_user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (trade_block_id, interested_user_id)
);

alter table public.trade_interest enable row level security;

drop policy if exists "Authenticated users can read trade interest" on public.trade_interest;
create policy "Authenticated users can read trade interest"
on public.trade_interest
for select
to authenticated
using (true);

drop policy if exists "Users can express their own interest" on public.trade_interest;
create policy "Users can express their own interest"
on public.trade_interest
for insert
to authenticated
with check (interested_user_id = auth.uid());

drop policy if exists "Users can withdraw their own interest" on public.trade_interest;
create policy "Users can withdraw their own interest"
on public.trade_interest
for delete
to authenticated
using (interested_user_id = auth.uid());
