-- Weekly power rankings, stored historically so movement (rank vs
-- previous_rank) doesn't need to be recomputed from scratch every time.
-- Written by src/lib/sync/power-rankings.ts. See docs/analytics.md for the
-- formula and weight config.

create table if not exists public.power_rankings (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons (id) on delete cascade,
  week integer not null,
  team_id bigint not null references public.fantasy_teams (id) on delete cascade,
  rank integer not null,
  previous_rank integer,
  power_score numeric not null,
  all_play_score numeric not null,
  points_score numeric not null,
  recent_score numeric not null,
  record_score numeric not null,
  roster_score numeric not null,
  created_at timestamptz not null default now(),
  unique (season_id, week, team_id)
);

create index if not exists power_rankings_season_week_idx on public.power_rankings (season_id, week);

alter table public.power_rankings enable row level security;

drop policy if exists "Authenticated users can read power rankings" on public.power_rankings;
create policy "Authenticated users can read power rankings"
on public.power_rankings
for select
to authenticated
using (true);
