-- Simple league-wide chat. Every authenticated league member can read and
-- post; a message's author is always the authenticated session's user_id
-- (never client-supplied) — the UI resolves the display name via profiles
-- at read time, never by trusting a client-sent name.

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_created_at_idx on public.chat_messages (created_at desc);

alter table public.chat_messages enable row level security;

drop policy if exists "Authenticated users can read chat" on public.chat_messages;
create policy "Authenticated users can read chat"
on public.chat_messages
for select
to authenticated
using (true);

drop policy if exists "Users can post chat as themselves" on public.chat_messages;
create policy "Users can post chat as themselves"
on public.chat_messages
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can delete their own messages" on public.chat_messages;
create policy "Users can delete their own messages"
on public.chat_messages
for delete
to authenticated
using (user_id = auth.uid());

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'chat_messages'
  ) then
    alter publication supabase_realtime add table public.chat_messages;
  end if;
end $$;
