-- Completed weekly recaps. Stored as a JSON payload (see
-- src/lib/analytics/recap.ts for the shape) rather than a column per
-- field — the recap's content is naturally a small nested document, and
-- keeping it flexible here means a later LLM-generated narrative field can
-- be added without a migration. season/week/created_at stay as real
-- columns since those are what queries filter and sort on.

create table if not exists public.weekly_recaps (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons (id) on delete cascade,
  week integer not null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  unique (season_id, week)
);

create index if not exists weekly_recaps_season_week_idx on public.weekly_recaps (season_id, week);

alter table public.weekly_recaps enable row level security;

drop policy if exists "Authenticated users can read weekly recaps" on public.weekly_recaps;
create policy "Authenticated users can read weekly recaps"
on public.weekly_recaps
for select
to authenticated
using (true);
