-- Configured YouTube channels + a cache of their latest videos, so the
-- Media page never calls YouTube at request time (see
-- src/lib/youtube/service.ts and src/lib/sync/youtube.ts).

create table if not exists public.youtube_channels (
  id bigint generated by default as identity primary key,
  name text not null,
  channel_id text not null unique,
  handle text,
  enabled boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.youtube_videos_cache (
  id bigint generated by default as identity primary key,
  channel_id text not null references public.youtube_channels (channel_id) on delete cascade,
  video_id text not null,
  title text not null,
  thumbnail_url text,
  published_at timestamptz,
  fetched_at timestamptz not null default now(),
  unique (channel_id, video_id)
);

create index if not exists youtube_videos_cache_channel_id_idx on public.youtube_videos_cache (channel_id, published_at desc);

alter table public.youtube_channels enable row level security;
alter table public.youtube_videos_cache enable row level security;

drop policy if exists "Authenticated users can read youtube channels" on public.youtube_channels;
create policy "Authenticated users can read youtube channels"
on public.youtube_channels
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read cached videos" on public.youtube_videos_cache;
create policy "Authenticated users can read cached videos"
on public.youtube_videos_cache
for select
to authenticated
using (true);

-- Seed the channel provided when this app was set up. Safe to re-run.
insert into public.youtube_channels (name, channel_id, enabled, display_order)
values ('League Channel', 'UCwVcTSzyshT2gMZZFhkiA-Q', true, 0)
on conflict (channel_id) do nothing;
